// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport/gloom.proto

package gloom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataStream_ObjStatus int32

const (
	DataStream_NEW     DataStream_ObjStatus = 0
	DataStream_STALE   DataStream_ObjStatus = 1
	DataStream_UPDATE  DataStream_ObjStatus = 2
	DataStream_DELETE  DataStream_ObjStatus = 3
	DataStream_CLOBBER DataStream_ObjStatus = 4
	DataStream_NOOP    DataStream_ObjStatus = 5
)

var DataStream_ObjStatus_name = map[int32]string{
	0: "NEW",
	1: "STALE",
	2: "UPDATE",
	3: "DELETE",
	4: "CLOBBER",
	5: "NOOP",
}

var DataStream_ObjStatus_value = map[string]int32{
	"NEW":     0,
	"STALE":   1,
	"UPDATE":  2,
	"DELETE":  3,
	"CLOBBER": 4,
	"NOOP":    5,
}

func (x DataStream_ObjStatus) String() string {
	return proto.EnumName(DataStream_ObjStatus_name, int32(x))
}

func (DataStream_ObjStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{5, 0}
}

type StatusResponse_NodeStatus int32

const (
	StatusResponse_AVAILABLE     StatusResponse_NodeStatus = 0
	StatusResponse_BOOTSTRAPPING StatusResponse_NodeStatus = 1
	StatusResponse_UNAVAILBLE    StatusResponse_NodeStatus = 2
)

var StatusResponse_NodeStatus_name = map[int32]string{
	0: "AVAILABLE",
	1: "BOOTSTRAPPING",
	2: "UNAVAILBLE",
}

var StatusResponse_NodeStatus_value = map[string]int32{
	"AVAILABLE":     0,
	"BOOTSTRAPPING": 1,
	"UNAVAILBLE":    2,
}

func (x StatusResponse_NodeStatus) String() string {
	return proto.EnumName(StatusResponse_NodeStatus_name, int32(x))
}

func (StatusResponse_NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{9, 0}
}

type RStatusResponse_NodeStatus int32

const (
	RStatusResponse_AVAILABLE     RStatusResponse_NodeStatus = 0
	RStatusResponse_BOOTSTRAPPING RStatusResponse_NodeStatus = 1
	RStatusResponse_UNAVAILBLE    RStatusResponse_NodeStatus = 2
)

var RStatusResponse_NodeStatus_name = map[int32]string{
	0: "AVAILABLE",
	1: "BOOTSTRAPPING",
	2: "UNAVAILBLE",
}

var RStatusResponse_NodeStatus_value = map[string]int32{
	"AVAILABLE":     0,
	"BOOTSTRAPPING": 1,
	"UNAVAILBLE":    2,
}

func (x RStatusResponse_NodeStatus) String() string {
	return proto.EnumName(RStatusResponse_NodeStatus_name, int32(x))
}

func (RStatusResponse_NodeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{11, 0}
}

type JoinRequest struct {
	NewNodeId            string   `protobuf:"bytes,1,opt,name=NewNodeId,proto3" json:"NewNodeId,omitempty"`
	NewAuth              string   `protobuf:"bytes,2,opt,name=NewAuth,proto3" json:"NewAuth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetNewNodeId() string {
	if m != nil {
		return m.NewNodeId
	}
	return ""
}

func (m *JoinRequest) GetNewAuth() string {
	if m != nil {
		return m.NewAuth
	}
	return ""
}

type GenResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenResponse) Reset()         { *m = GenResponse{} }
func (m *GenResponse) String() string { return proto.CompactTextString(m) }
func (*GenResponse) ProtoMessage()    {}
func (*GenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{1}
}

func (m *GenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenResponse.Unmarshal(m, b)
}
func (m *GenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenResponse.Marshal(b, m, deterministic)
}
func (m *GenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenResponse.Merge(m, src)
}
func (m *GenResponse) XXX_Size() int {
	return xxx_messageInfo_GenResponse.Size(m)
}
func (m *GenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenResponse proto.InternalMessageInfo

func (m *GenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type NAuthRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Auth                 string   `protobuf:"bytes,2,opt,name=Auth,proto3" json:"Auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NAuthRequest) Reset()         { *m = NAuthRequest{} }
func (m *NAuthRequest) String() string { return proto.CompactTextString(m) }
func (*NAuthRequest) ProtoMessage()    {}
func (*NAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{2}
}

func (m *NAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NAuthRequest.Unmarshal(m, b)
}
func (m *NAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NAuthRequest.Marshal(b, m, deterministic)
}
func (m *NAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NAuthRequest.Merge(m, src)
}
func (m *NAuthRequest) XXX_Size() int {
	return xxx_messageInfo_NAuthRequest.Size(m)
}
func (m *NAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NAuthRequest proto.InternalMessageInfo

func (m *NAuthRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NAuthRequest) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

type AuthRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SubId                string   `protobuf:"bytes,2,opt,name=SubId,proto3" json:"SubId,omitempty"`
	Auth                 string   `protobuf:"bytes,3,opt,name=Auth,proto3" json:"Auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{3}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AuthRequest) GetSubId() string {
	if m != nil {
		return m.SubId
	}
	return ""
}

func (m *AuthRequest) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

type BalanceRequest struct {
	KeyStart             uint64   `protobuf:"varint,1,opt,name=KeyStart,proto3" json:"KeyStart,omitempty"`
	KeyEnd               uint64   `protobuf:"varint,2,opt,name=KeyEnd,proto3" json:"KeyEnd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{4}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetKeyStart() uint64 {
	if m != nil {
		return m.KeyStart
	}
	return 0
}

func (m *BalanceRequest) GetKeyEnd() uint64 {
	if m != nil {
		return m.KeyEnd
	}
	return 0
}

type DataStream struct {
	ObjKey               string       `protobuf:"bytes,1,opt,name=ObjKey,proto3" json:"ObjKey,omitempty"`
	Auth                 *AuthRequest `protobuf:"bytes,2,opt,name=Auth,proto3" json:"Auth,omitempty"`
	Sum                  uint64       `protobuf:"varint,3,opt,name=Sum,proto3" json:"Sum,omitempty"`
	Payload              []byte       `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Location             int64        `protobuf:"varint,5,opt,name=Location,proto3" json:"Location,omitempty"`
	Timestamp            int64        `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataStream) Reset()         { *m = DataStream{} }
func (m *DataStream) String() string { return proto.CompactTextString(m) }
func (*DataStream) ProtoMessage()    {}
func (*DataStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{5}
}

func (m *DataStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataStream.Unmarshal(m, b)
}
func (m *DataStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataStream.Marshal(b, m, deterministic)
}
func (m *DataStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataStream.Merge(m, src)
}
func (m *DataStream) XXX_Size() int {
	return xxx_messageInfo_DataStream.Size(m)
}
func (m *DataStream) XXX_DiscardUnknown() {
	xxx_messageInfo_DataStream.DiscardUnknown(m)
}

var xxx_messageInfo_DataStream proto.InternalMessageInfo

func (m *DataStream) GetObjKey() string {
	if m != nil {
		return m.ObjKey
	}
	return ""
}

func (m *DataStream) GetAuth() *AuthRequest {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *DataStream) GetSum() uint64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *DataStream) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DataStream) GetLocation() int64 {
	if m != nil {
		return m.Location
	}
	return 0
}

func (m *DataStream) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type NewObjectRequest struct {
	NewKey               string       `protobuf:"bytes,1,opt,name=NewKey,proto3" json:"NewKey,omitempty"`
	Auth                 *AuthRequest `protobuf:"bytes,2,opt,name=Auth,proto3" json:"Auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewObjectRequest) Reset()         { *m = NewObjectRequest{} }
func (m *NewObjectRequest) String() string { return proto.CompactTextString(m) }
func (*NewObjectRequest) ProtoMessage()    {}
func (*NewObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{6}
}

func (m *NewObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewObjectRequest.Unmarshal(m, b)
}
func (m *NewObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewObjectRequest.Marshal(b, m, deterministic)
}
func (m *NewObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewObjectRequest.Merge(m, src)
}
func (m *NewObjectRequest) XXX_Size() int {
	return xxx_messageInfo_NewObjectRequest.Size(m)
}
func (m *NewObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewObjectRequest proto.InternalMessageInfo

func (m *NewObjectRequest) GetNewKey() string {
	if m != nil {
		return m.NewKey
	}
	return ""
}

func (m *NewObjectRequest) GetAuth() *AuthRequest {
	if m != nil {
		return m.Auth
	}
	return nil
}

type NewObjectResponse struct {
	NewObjKeys           []byte   `protobuf:"bytes,1,opt,name=NewObjKeys,proto3" json:"NewObjKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewObjectResponse) Reset()         { *m = NewObjectResponse{} }
func (m *NewObjectResponse) String() string { return proto.CompactTextString(m) }
func (*NewObjectResponse) ProtoMessage()    {}
func (*NewObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{7}
}

func (m *NewObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewObjectResponse.Unmarshal(m, b)
}
func (m *NewObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewObjectResponse.Marshal(b, m, deterministic)
}
func (m *NewObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewObjectResponse.Merge(m, src)
}
func (m *NewObjectResponse) XXX_Size() int {
	return xxx_messageInfo_NewObjectResponse.Size(m)
}
func (m *NewObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewObjectResponse proto.InternalMessageInfo

func (m *NewObjectResponse) GetNewObjKeys() []byte {
	if m != nil {
		return m.NewObjKeys
	}
	return nil
}

type StatusRequest struct {
	StatusNodeId         string   `protobuf:"bytes,1,opt,name=StatusNodeId,proto3" json:"StatusNodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{8}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetStatusNodeId() string {
	if m != nil {
		return m.StatusNodeId
	}
	return ""
}

type StatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{9}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

type RStatusRequest struct {
	RemoteNodeId         string   `protobuf:"bytes,1,opt,name=RemoteNodeId,proto3" json:"RemoteNodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RStatusRequest) Reset()         { *m = RStatusRequest{} }
func (m *RStatusRequest) String() string { return proto.CompactTextString(m) }
func (*RStatusRequest) ProtoMessage()    {}
func (*RStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{10}
}

func (m *RStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RStatusRequest.Unmarshal(m, b)
}
func (m *RStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RStatusRequest.Marshal(b, m, deterministic)
}
func (m *RStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RStatusRequest.Merge(m, src)
}
func (m *RStatusRequest) XXX_Size() int {
	return xxx_messageInfo_RStatusRequest.Size(m)
}
func (m *RStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RStatusRequest proto.InternalMessageInfo

func (m *RStatusRequest) GetRemoteNodeId() string {
	if m != nil {
		return m.RemoteNodeId
	}
	return ""
}

type RStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RStatusResponse) Reset()         { *m = RStatusResponse{} }
func (m *RStatusResponse) String() string { return proto.CompactTextString(m) }
func (*RStatusResponse) ProtoMessage()    {}
func (*RStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{11}
}

func (m *RStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RStatusResponse.Unmarshal(m, b)
}
func (m *RStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RStatusResponse.Marshal(b, m, deterministic)
}
func (m *RStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RStatusResponse.Merge(m, src)
}
func (m *RStatusResponse) XXX_Size() int {
	return xxx_messageInfo_RStatusResponse.Size(m)
}
func (m *RStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RStatusResponse proto.InternalMessageInfo

type InvNodeRequest struct {
	InvNodeId            string   `protobuf:"bytes,1,opt,name=InvNodeId,proto3" json:"InvNodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvNodeRequest) Reset()         { *m = InvNodeRequest{} }
func (m *InvNodeRequest) String() string { return proto.CompactTextString(m) }
func (*InvNodeRequest) ProtoMessage()    {}
func (*InvNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{12}
}

func (m *InvNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvNodeRequest.Unmarshal(m, b)
}
func (m *InvNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvNodeRequest.Marshal(b, m, deterministic)
}
func (m *InvNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvNodeRequest.Merge(m, src)
}
func (m *InvNodeRequest) XXX_Size() int {
	return xxx_messageInfo_InvNodeRequest.Size(m)
}
func (m *InvNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvNodeRequest proto.InternalMessageInfo

func (m *InvNodeRequest) GetInvNodeId() string {
	if m != nil {
		return m.InvNodeId
	}
	return ""
}

type InvNodeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvNodeResponse) Reset()         { *m = InvNodeResponse{} }
func (m *InvNodeResponse) String() string { return proto.CompactTextString(m) }
func (*InvNodeResponse) ProtoMessage()    {}
func (*InvNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6543115fca936db, []int{13}
}

func (m *InvNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvNodeResponse.Unmarshal(m, b)
}
func (m *InvNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvNodeResponse.Marshal(b, m, deterministic)
}
func (m *InvNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvNodeResponse.Merge(m, src)
}
func (m *InvNodeResponse) XXX_Size() int {
	return xxx_messageInfo_InvNodeResponse.Size(m)
}
func (m *InvNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvNodeResponse proto.InternalMessageInfo

func (m *InvNodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("gloom.DataStream_ObjStatus", DataStream_ObjStatus_name, DataStream_ObjStatus_value)
	proto.RegisterEnum("gloom.StatusResponse_NodeStatus", StatusResponse_NodeStatus_name, StatusResponse_NodeStatus_value)
	proto.RegisterEnum("gloom.RStatusResponse_NodeStatus", RStatusResponse_NodeStatus_name, RStatusResponse_NodeStatus_value)
	proto.RegisterType((*JoinRequest)(nil), "gloom.JoinRequest")
	proto.RegisterType((*GenResponse)(nil), "gloom.GenResponse")
	proto.RegisterType((*NAuthRequest)(nil), "gloom.NAuthRequest")
	proto.RegisterType((*AuthRequest)(nil), "gloom.AuthRequest")
	proto.RegisterType((*BalanceRequest)(nil), "gloom.BalanceRequest")
	proto.RegisterType((*DataStream)(nil), "gloom.DataStream")
	proto.RegisterType((*NewObjectRequest)(nil), "gloom.NewObjectRequest")
	proto.RegisterType((*NewObjectResponse)(nil), "gloom.NewObjectResponse")
	proto.RegisterType((*StatusRequest)(nil), "gloom.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "gloom.StatusResponse")
	proto.RegisterType((*RStatusRequest)(nil), "gloom.RStatusRequest")
	proto.RegisterType((*RStatusResponse)(nil), "gloom.RStatusResponse")
	proto.RegisterType((*InvNodeRequest)(nil), "gloom.InvNodeRequest")
	proto.RegisterType((*InvNodeResponse)(nil), "gloom.InvNodeResponse")
}

func init() { proto.RegisterFile("transport/gloom.proto", fileDescriptor_d6543115fca936db) }

var fileDescriptor_d6543115fca936db = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6f, 0xda, 0x3a,
	0x14, 0x26, 0x10, 0x28, 0x1c, 0x28, 0x4d, 0x7d, 0xdb, 0x5e, 0x84, 0xae, 0xae, 0x2a, 0x3f, 0x6c,
	0x48, 0x93, 0xba, 0xa9, 0xdd, 0x2f, 0x75, 0xd2, 0xa4, 0x00, 0x51, 0xc5, 0x40, 0x09, 0x73, 0xe8,
	0xf6, 0x6c, 0xc0, 0xda, 0xa8, 0x20, 0x61, 0xc4, 0x0c, 0xf1, 0xba, 0xff, 0x76, 0xff, 0xc5, 0xe4,
	0x38, 0x0e, 0x0e, 0x5d, 0xb5, 0x69, 0xda, 0x5b, 0xbe, 0xcf, 0xe7, 0x7c, 0x3e, 0xf6, 0xf9, 0x8e,
	0x03, 0xa7, 0x7c, 0x45, 0x83, 0x68, 0x19, 0xae, 0xf8, 0xd3, 0x4f, 0xf3, 0x30, 0x5c, 0x5c, 0x2c,
	0x57, 0x21, 0x0f, 0x51, 0x31, 0x06, 0xd8, 0x81, 0xea, 0xbb, 0x70, 0x16, 0x10, 0xf6, 0x65, 0xcd,
	0x22, 0x8e, 0xfe, 0x83, 0x8a, 0xcb, 0x36, 0x6e, 0x38, 0x65, 0xbd, 0x69, 0xc3, 0x38, 0x37, 0x5a,
	0x15, 0xb2, 0x23, 0x50, 0x03, 0x0e, 0x5c, 0xb6, 0xb1, 0xd7, 0xfc, 0x73, 0x23, 0x1f, 0xaf, 0x29,
	0x88, 0x1f, 0x43, 0xf5, 0x86, 0x05, 0x84, 0x45, 0xcb, 0x30, 0x88, 0x98, 0x08, 0xf4, 0xd7, 0x93,
	0x09, 0x8b, 0xa2, 0x58, 0xa4, 0x4c, 0x14, 0xc4, 0xd7, 0x50, 0x73, 0x45, 0x86, 0xda, 0xf0, 0x0c,
	0x4a, 0x99, 0xdd, 0x12, 0x84, 0x10, 0x98, 0xda, 0x3e, 0xf1, 0x37, 0xf6, 0xa1, 0xaa, 0xa7, 0x36,
	0xa1, 0xdc, 0x99, 0xcf, 0x58, 0xc0, 0xd3, 0xe4, 0x14, 0xa3, 0x13, 0x28, 0xfa, 0xeb, 0x71, 0x6f,
	0x9a, 0xe4, 0x4b, 0x90, 0x8a, 0x16, 0x34, 0xd1, 0x2e, 0xd4, 0xdb, 0x74, 0x4e, 0x83, 0x09, 0xd3,
	0x74, 0xfb, 0x6c, 0xeb, 0x73, 0xba, 0xe2, 0xb1, 0xae, 0x49, 0x52, 0x2c, 0xca, 0xed, 0xb3, 0xad,
	0x13, 0x48, 0x61, 0x93, 0x24, 0x08, 0x7f, 0xcb, 0x03, 0x74, 0x29, 0xa7, 0x3e, 0x5f, 0x31, 0xba,
	0x10, 0x61, 0xde, 0xf8, 0xae, 0xcf, 0xb6, 0xea, 0x54, 0x12, 0xa1, 0x47, 0xda, 0xa9, 0xaa, 0x97,
	0xe8, 0x42, 0x36, 0x44, 0x3b, 0x94, 0x2c, 0x0a, 0x59, 0x50, 0xf0, 0xd7, 0x8b, 0xb8, 0x4e, 0x93,
	0x88, 0x4f, 0x71, 0xa3, 0x43, 0xba, 0x9d, 0x87, 0x74, 0xda, 0x30, 0xcf, 0x8d, 0x56, 0x8d, 0x28,
	0x28, 0xca, 0x1d, 0x84, 0x13, 0xca, 0x67, 0x61, 0xd0, 0x28, 0x9e, 0x1b, 0xad, 0x02, 0x49, 0xb1,
	0x68, 0xe7, 0x68, 0xb6, 0x60, 0x11, 0xa7, 0x8b, 0x65, 0xa3, 0x14, 0x2f, 0xee, 0x08, 0xec, 0x42,
	0xc5, 0x1b, 0xdf, 0xf9, 0x9c, 0xf2, 0x75, 0x84, 0x0e, 0xa0, 0xe0, 0x3a, 0x1f, 0xad, 0x1c, 0xaa,
	0x40, 0xd1, 0x1f, 0xd9, 0x03, 0xc7, 0x32, 0x10, 0x40, 0xe9, 0x76, 0xd8, 0xb5, 0x47, 0x8e, 0x95,
	0x17, 0xdf, 0x5d, 0x67, 0xe0, 0x8c, 0x1c, 0xab, 0x80, 0xaa, 0x70, 0xd0, 0x19, 0x78, 0xed, 0xb6,
	0x43, 0x2c, 0x13, 0x95, 0xc1, 0x74, 0x3d, 0x6f, 0x68, 0x15, 0x31, 0x01, 0xcb, 0x65, 0x1b, 0x6f,
	0x7c, 0xc7, 0x26, 0x5c, 0xef, 0x2f, 0xdb, 0x68, 0x37, 0x21, 0xd1, 0xef, 0xde, 0x04, 0xbe, 0x82,
	0x63, 0x4d, 0x33, 0xb1, 0xd7, 0xff, 0x00, 0x92, 0xec, 0xb3, 0xad, 0x74, 0x58, 0x8d, 0x68, 0x0c,
	0xbe, 0x82, 0x43, 0x79, 0x2a, 0x55, 0x05, 0x86, 0x9a, 0x24, 0x32, 0x5e, 0xcb, 0x70, 0x78, 0x08,
	0x75, 0x95, 0x24, 0xb7, 0xc1, 0x6f, 0x01, 0xc4, 0x5a, 0x72, 0x41, 0x87, 0x50, 0xb1, 0x3f, 0xd8,
	0xbd, 0x81, 0xdd, 0x1e, 0x38, 0x56, 0x0e, 0x1d, 0xc3, 0x61, 0xdb, 0xf3, 0x46, 0xfe, 0x88, 0xd8,
	0xc3, 0x61, 0xcf, 0xbd, 0xb1, 0x0c, 0x54, 0x07, 0xb8, 0x75, 0xe3, 0x18, 0x11, 0x92, 0xc7, 0xcf,
	0xa1, 0x4e, 0xee, 0xd5, 0x41, 0xd8, 0x22, 0xe4, 0x2c, 0x5b, 0x87, 0xce, 0xe1, 0xf7, 0x70, 0x44,
	0xfe, 0x72, 0x21, 0x17, 0x50, 0xef, 0x05, 0x5f, 0x85, 0x84, 0x36, 0xe7, 0x09, 0xb3, 0x9b, 0xf3,
	0x94, 0xc0, 0x4f, 0xe0, 0x28, 0x8d, 0xff, 0xd5, 0x44, 0x5f, 0x7e, 0x37, 0xa1, 0x78, 0x23, 0xba,
	0x87, 0x5e, 0xc9, 0xb7, 0xa4, 0x33, 0x5f, 0x47, 0x9c, 0xad, 0x90, 0x6a, 0xaa, 0xf6, 0xbe, 0x34,
	0x15, 0xa7, 0x3d, 0x16, 0x38, 0x87, 0x5e, 0x40, 0x59, 0x34, 0x5b, 0x6c, 0x88, 0xfe, 0x49, 0x22,
	0xf4, 0x57, 0xe2, 0x81, 0xb4, 0x97, 0x00, 0x22, 0x48, 0x0e, 0x3d, 0xfa, 0x89, 0x87, 0x1e, 0xc8,
	0xbb, 0x86, 0x6a, 0x32, 0xf2, 0xc2, 0x2d, 0xe8, 0x34, 0x09, 0xca, 0x3e, 0x03, 0x0f, 0xe4, 0xbe,
	0x56, 0xad, 0x88, 0xe7, 0xfc, 0x38, 0x89, 0xd9, 0x8d, 0x7e, 0xf3, 0x3e, 0x85, 0x73, 0x2d, 0xe3,
	0x99, 0x81, 0xae, 0xa1, 0x26, 0x2b, 0xfd, 0x83, 0x5c, 0x5b, 0x19, 0x9e, 0x4d, 0x78, 0x84, 0xfe,
	0x55, 0x57, 0xb4, 0x37, 0x6c, 0xcd, 0xc6, 0xfd, 0x85, 0xb4, 0xf0, 0x37, 0x19, 0x0f, 0x9d, 0x24,
	0x91, 0x19, 0x7b, 0x36, 0x4f, 0xf7, 0xd8, 0x34, 0xb9, 0xa3, 0x7c, 0x9b, 0xa4, 0xab, 0xc0, 0xac,
	0xbd, 0x9b, 0x67, 0xfb, 0xb4, 0x12, 0x48, 0x0e, 0x21, 0x5c, 0x48, 0xe7, 0xb3, 0x29, 0x95, 0x66,
	0x4f, 0x65, 0xb2, 0xe6, 0x4c, 0x65, 0xf6, 0x3c, 0x88, 0x73, 0xe3, 0x52, 0xfc, 0xef, 0xba, 0xfa,
	0x11, 0x00, 0x00, 0xff, 0xff, 0x54, 0x79, 0xf7, 0xfe, 0xd4, 0x06, 0x00, 0x00,
}
